FROM ruby:2.4.0

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  less \
  libpq-dev \
  nodejs \
  qt5-default \
  libqt5webkit5-dev \
  gstreamer1.0-plugins-base \
  gstreamer1.0-tools \
  gstreamer1.0-x \
  xvfb

RUN ln -s /usr/bin/nodejs /usr/bin/node

ENV SHELL /bin/bash

RUN mkdir /app
WORKDIR /app

COPY Gemfile* /app/
RUN bundle install
