version: '3'

volumes:
  db_data: {}

services:
  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data

  web: &web
    image: civica-digital/tu-ciudad-tus-datos:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=
      - DATABASE_USERNAME=postgres
      - SPRING_PIDFILE=tmp/spring.pid
      - SPRING_SOCKET=tmp/spring.sock
      - SPRING_TMP_PATH=tmp

  spring:
    <<: *web
    command: spring server
    restart: unless-stopped
