version: '3'

volumes:
  db_data: {}

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: 472554934874.dkr.ecr.us-east-1.amazonaws.com/tu-ciudad-tus-datos
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    labels:
      - "traefik.backend=tu-ciudad-tus-datos-web"
      - "traefik.frontend.rule=Host:tu-ciudad-tus-datos.civicadesarrolla.me"
      - "traefik.enable=true"
      - "traefik.port=3000"

  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
